apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres-deployment
spec:
 replicas: 1
 selector: 
  matchLabels:
   component: postgres
 template: 
  metadata:
   labels: 
    component: postgres
  spec:
   volumes: #PVC volume specified.
     - name: postgres-storage
       persistentVolumeClaim: 
        claimName: database-persistent-volume-claim
   containers:
    - name: postgres
      image: postgres
      ports:
       - containerPort: 5432
      volumeMounts:
       - name: postgres-storage #It refers to the PVC section and gets the volume with the name to mount on the container.
         mountPath: /var/lib/postgresql/data #It is the default path where postgres store its data.
         subPath: postgres #it means that any data stored in the mountPath will be stored in the subpath folder name in the PVC. 
      env: #We will overide the default PGPASSWORD with the one that we created as a secrets object.
       - name: POSTGRES_PASSWORD
         valueFrom:
          secretKeyRef:
           name: pgpassword
           key: PGPASSWORD
          