apiVersion: apps/v1
kind: Deployment
metadata:
 name: server-deployment
spec: 
 replicas: 3
 selector:
  matchLabels:
   component: server
 template:
  metadata:
   labels:
    component: server
  spec:
   containers:
    - name: server
      image: stephengrider/multi-server
      ports:
       - containerPort: 5000
      env: # environment variable for redis and postgres to get connected.  
       - name: REDIS_HOST
         value: redis-cluster-ip-service
       - name: REDIS_PORT
         value: '6379'
       - name: PGUSER
         value: postgres
       - name: PGHOST
         value: postgres-cluster-ip-service
       - name: PGPORT
         value: '5432'
       - name: PGDATABASE
         value: postgres #this is the default postgres database. 
       - name: PGPASSWORD
         valueFrom: #Here we will placing the secret that we created.
          secretKeyRef:
           name: pgpassword #it is the name that we had given while creating the secret
           key: PGPASSWORD  #it is the key of the key=value pair that we created while creating the secret. 
